class AuditEvents:
    LOGIN_SUCCESS = ("AUTH001", "LOGIN_SUCCESS")
    LOGIN_FAILED = ("AUTH002", "LOGIN_FAILED")

    LICENSE_CHECK = ("LIC001", "LICENSE_CHECK")
    LICENSE_ACTIVATED = ("LIC002", "LICENSE_ACTIVATED")
    LICENSE_DEACTIVATED = ("LIC003", "LICENSE_DEACTIVATED")
    LICENSE_EXPIRED = ("LIC004", "LICENSE_EXPIRED")

    DEVICE_REGISTERED = ("DEV001", "DEVICE_REGISTERED")
    DEVICE_AUTHORIZED = ("DEV002", "DEVICE_AUTHORIZED")
    DEVICE_BLOCKED = ("DEV003", "DEVICE_BLOCKED")
    DEVICE_REMOVED = ("DEV004", "DEVICE_REMOVED")
    DEVICE_LIMIT_REACHED = ("DEV005", "DEVICE_LIMIT_REACHED")

    FINGERPRINT_MISMATCH = ("SEC001", "FINGERPRINT_MISMATCH")
    INVALID_TOKEN = ("SEC002", "INVALID_TOKEN")
    INVALID_OFFLINE_TICKET = ("SEC003", "INVALID_OFFLINE_TICKET")

    OFFLINE_TICKET_CREATED = ("TKT001", "OFFLINE_TICKET_CREATED")
    OFFLINE_TICKET_REVOKED = ("TKT002", "OFFLINE_TICKET_REVOKED")
    OFFLINE_TICKET_EXPIRED = ("TKT003", "OFFLINE_TICKET_EXPIRED")

    HEARTBEAT_RECEIVED = ("HB001", "HEARTBEAT_RECEIVED")
    CLIENT_ONLINE = ("HB002", "CLIENT_ONLINE")
    CLIENT_OFFLINE = ("HB003", "CLIENT_OFFLINE")
