"""baseline inicial

Revision ID: 998745b250e8
Revises: 
Create Date: 2026-07-10 13:43:01.461329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '998745b250e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('min_required_version', sa.String(), nullable=False),
    sa.Column('download_url', sa.String(), nullable=False),
    sa.Column('changelog', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('obrigatorio', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_updates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_updates_id'), ['id'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('event_code', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('fingerprint', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_id'), ['id'], unique=False)

    op.create_table('dispositivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('nome_maquina', sa.String(), nullable=True),
    sa.Column('sistema', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('fingerprint', sa.String(), nullable=True),
    sa.Column('ultimo_ip', sa.String(), nullable=True),
    sa.Column('ultimo_acesso', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dispositivos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispositivos_id'), ['id'], unique=False)

    op.create_table('licencas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('plano', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('limite_dispositivos', sa.Integer(), nullable=True),
    sa.Column('expira_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('licencas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_licencas_id'), ['id'], unique=False)

    op.create_table('offline_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=False),
    sa.Column('fingerprint', sa.String(), nullable=True),
    sa.Column('emitido_em', sa.DateTime(), nullable=True),
    sa.Column('valido_ate', sa.DateTime(), nullable=False),
    sa.Column('revogado', sa.Boolean(), nullable=True),
    sa.Column('revogado_em', sa.DateTime(), nullable=True),
    sa.Column('motivo_revogacao', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('offline_tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offline_tickets_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_offline_tickets_ticket_id'), ['ticket_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offline_tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offline_tickets_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_offline_tickets_id'))

    op.drop_table('offline_tickets')
    with op.batch_alter_table('licencas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_licencas_id'))

    op.drop_table('licencas')
    with op.batch_alter_table('dispositivos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispositivos_id'))

    op.drop_table('dispositivos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('app_updates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_updates_id'))

    op.drop_table('app_updates')
    # ### end Alembic commands ###
